# Except payment gateway
all_urls = {
    "admin": "/admin/",
    "cart": "/cart/",
    "store": "/store/",
    "home": "/",
    "login": "/login/",
    "signup": "/signup/",
    "sell": "/sell/",
    "sell_new": "/sell/new",
    "sell_pending_rejected": "/sell/pending_rejected",
    "sell_listed": "/sell/listed",
    "sell_sold": "/sell/sold",
    "purchases": "/purchases/",
    "custom_payment": "/payment/",
    "cancel": "/payment/cancel",
    "item": "/item/",
    "checkout": "/checkout/",
    "profile": "/profile/",
    "logout": "/logout/",
    "search": "/search/",
    "admin_response_to_new_item_request": "/item_handler/",
    "admin_response_to_seller_request": "/seller_handler/",
    "email_token":"/token/",
    "email_verified":"/email_verified/",
    "verify_token":"/verify/<auth_token>",
    "verification_error":"/error",

}
