# Generated by Django 3.2.8 on 2021-11-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(blank=True, default=None, null=True)),
                ('item_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('buyer_id', models.IntegerField(blank=True, default=None, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
    ]
