# Generated by Django 3.2.10 on 2021-12-11 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='New_Product_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('image_1', models.CharField(max_length=1000)),
                ('image_2', models.CharField(max_length=1000)),
                ('image_3', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_4', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_5', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=2000)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
